[fish-rose-pine]
src.git = "https://github.com/rose-pine/fish"
fetch.git = "https://github.com/rose-pine/fish"

[fish-catppuccin]
src.git = "https://github.com/catppuccin/fish"
fetch.git = "https://github.com/catppuccin/fish"

[fish-tokyonight]
src.github_tag = "vitallium/tokyonight-fish"
fetch.github = "vitallium/tokyonight-fish"

[p5r-grub]
src.github_tag = "SiriusAhu/Persona_5_Royal_Grub_Themes"
fetch.github = "SiriusAhu/Persona_5_Royal_Grub_Themes"

[ocenaudio-bin]
src.cmd = "curl --silent https://www.ocenaudio.com/changelog | sed -n 's%.*href=\"/download?version=v\\([^\"]*\\).*%\\1%p' | head -1"
fetch.url = "https://www.ocenaudio.com/downloads/index.php/ocenaudio_universal.dmg?version=v$ver"

[shflags]
src.github_tag = "kward/shflags"
fetch.github = "kward/shflags"

[iqm]
src.git = "https://github.com/lsalzman/iqm"
fetch.git = "https://github.com/lsalzman/iqm"

[hatsune-miku-cursor]
src.github_tag = "supermariofps/hatsune-miku-windows-linux-cursors"
fetch.github = "supermariofps/hatsune-miku-windows-linux-cursors"

# Shaders

[artcnn]
src.github_tag = "Artoriuz/ArtCNN"
fetch.github = "Artoriuz/ArtCNN"

[mpv-retro-shaders]
src.git = "https://github.com/hhirtz/mpv-retro-shaders"
fetch.git = "https://github.com/hhirtz/mpv-retro-shaders"

# Fonts

[ia-writer]
src.git = "https://github.com/iaolo/iA-Fonts"
fetch.git = "https://github.com/iaolo/iA-Fonts"

[sf-mono-font]
src.git = "https://github.com/supercomputra/SF-Mono-Font"
fetch.git = "https://github.com/supercomputra/SF-Mono-Font"

[sf-mono-nf-liga]
src.git = "https://github.com/shaunsingh/SFMono-Nerd-Font-Ligaturized"
fetch.git = "https://github.com/shaunsingh/SFMono-Nerd-Font-Ligaturized"

[prchann-font-collection]
src.git = "https://github.com/prchann/fonts"
fetch.git = "https://github.com/prchann/fonts"
